global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using SoundPlay.DAL.Models;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore.Query;
global using System.Linq.Expressions;
global using SoundPlay.DAL.Data;
global using SoundPlay.DAL.Repository.Interfaces;
