global using Microsoft.EntityFrameworkCore;
global using System.Linq.Expressions;
global using SoundPlay.Core.Interfaces;
global using SoundPlay.Core.Models;
global using SoundPlay.Core;
global using SoundPlay.Core.Extensions;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Query;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;